language: php

branches:
  only:
    - dev

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=1

before_install:
  - composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
  - composer install --dev

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
